### ISSUE TITLE
switch cjs to esm for npm

### ISSUE THREAD

**Issue by jimmywarting** [nats-io/nkeys.js#15]
time to switch cjs to esm?
slapp in `"type": "module"`

**Comment by aricart** [comment]
For some reason, when we do that it makes it difficult to use in React.

**Comment by jimmywarting** [comment]
bah, jsx... hate it. Remember being linked to some issue about react not supporting esm only packages... react should fix it!

**Comment by aricart** [comment]
Yes for some reason their build process will fail on basic stuff.

**Comment by jimmywarting** [comment]
I have never been a fan of react/jsx cuz it's not pure html, can't use class, must use className, can't use `style=""` normally must be a object etc
